require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

use_flipper!({'Flipper-Folly' => '2.3.0' })

target 'appgobarber' do
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # Pods for appgobarber

  target 'appgobarber-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appgobarberTests' do
    inherit! :search_paths
    # Pods for testing
  end

end