require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


target 'goairtech' do
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # Pods for goairtech

  target 'goairtech-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'goairtechTests' do
    inherit! :search_paths
    # Pods for testing
  end

end